name: Solidity

on: [push, pull_request]

jobs:
  check-copyright:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: License header
        run: .scripts/check-copyright-notice.sh
      - name: Authors
        run: .scripts/check-notice-authors.sh origin/main

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: npx solhint 'contracts/**/*.sol'

      - name: Install Hardhat and other dependencies
        run: |
          yarn add --dev hardhat
          yarn add --dev ts-node
          yarn add --dev @nomicfoundation/hardhat-toolbox
          yarn add --dev @nomicfoundation/hardhat-chai-matchers@^2.0.0
          yarn add --dev @nomicfoundation/hardhat-ethers@^3.0.0
          yarn add --dev @nomicfoundation/hardhat-ignition-ethers@^0.15.0
          yarn add --dev @nomicfoundation/hardhat-network-helpers@^1.0.0
          yarn add --dev @nomicfoundation/hardhat-verify@^2.0.0
          yarn add --dev @typechain/ethers-v6@^0.5.0
          yarn add --dev @typechain/hardhat@^9.0.0
          yarn add --dev hardhat-gas-reporter@^1.0.8
          yarn add --dev @nomicfoundation/hardhat-ignition@^0.15.5
          yarn add --dev @nomicfoundation/ignition-core@^0.15.5

      - name: Compile
        run: npx hardhat compile

      - name: Static analysis
        run: |
          pip3 install slither-analyzer==0.8.3
          slither --exclude solc-version,timestamp,boolean-equality,unimplemented-functions,locked-ether --filter-paths vendor/ .
          # Alternatively, one can use Docker:
          # WORKDIR=/share docker run --rm -v $(pwd):$WORKDIR -w $WORKDIR --entrypoint slither trailofbits/eth-security-toolbox [insert slither parameters here]

      - name: Test
        run: npx hardhat test

